#!/bin/bash

echo "Running git pre-commit hook"
#echo $JAVA_HOME
#pwd
#source .bashrc

#./gradlew backend:test     # TODO fix, gitkraken now doesn't resolve env variables and java_home is not found

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0