#!/bin/bash

echo "Running git pre-commit hook"

#./gradlew backend:test        ### TODO git kraken can't find java_home and I'm only able to commit from terminal, fix later

RESULT=$?

# return 1 exit code if running checks fails
[ $RESULT -ne 0 ] && exit 1
exit 0