CREATE TABLE IF NOT EXISTS weighings (date TIMESTAMP NOT NULL, weight FLOAT NOT NULL, id BIGSERIAL NOT NULL PRIMARY KEY );
CREATE TABLE IF NOT EXISTS users (username VARCHAR(30) UNIQUE NOT NULL, password_hash VARCHAR(100) NOT NULL, id BIGSERIAL NOT NULL PRIMARY KEY );
CREATE TABLE IF NOT EXISTS refresh_tokens (refresh_token VARCHAR(500) NOT NULL, user_id BIGINT NOT NULL);
