name: Build and Publish
on: [ push, pull_request ]
jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1.0.3

      - name: Build devRelease apk if develop branch
        if: github.ref == 'refs/heads/develop'
        run: ./gradlew assembleDevRelease

      - name: Sign devRelease APK if develop branch
        uses: r0adkll/sign-android-release@v1
        if: github.ref == 'refs/heads/develop'
        # ID used to access action output
        id: sign_dev_release_app
        with:
          releaseDirectory: android/build/outputs/apk/dev/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "30.0.2"

      - name: Upload devRelease to Firebase App Distribution if develop branch
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        if: github.ref == 'refs/heads/develop'
        with:
          appId: ${{secrets.FIREBASE_DEV_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: android_dev_testers
          file: ${{steps.sign_dev_release_app.outputs.signedReleaseFile}}

      # TODO NETLIFY DEPLOY AFTER browserDistribution + api type from env in gradle?

#      # If main branch update, deploy to gh-pages
#      - name: Deploy
#        if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main'
#        uses: JamesIves/github-pages-deploy-action@3.7.1
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          BRANCH: gh-pages # The branch the action should deploy to.
#          FOLDER: build/distributions # The folder the action should deploy.
#          CLEAN: true # Automatically remove deleted files from the deploy branch